### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by wojtekKrol** [haystackeditor/haystack-editor#29] opened 2024-10-14 12:30 UTC
Could you consider making it as a plugin to VSCode instead of a new IDE based on VSCode? 

It would be great to have it as plugin so I could just install it and use with cursor.ai

**Comment by AkshaySG14** [comment] 2024-10-14 13:49
Duplicate of https://github.com/haystackeditor/haystack-editor/issues/6

**Closed by AkshaySG14** 2024-10-14 13:49 UTC
